services:
  token-api:
    build: .
    container_name: ugreen-api-token
    ports:
      - "4115:4115"
    environment:
      API_SCHEME: "https"
      API_HOST: "192.168.xxx.xx"
      API_PORT: "9443"
      API_VERIFY: "false"
    restart: unless-stopped
