version: "3.8"
services:
  ugreen-api-token:
    build: .
    container_name: ugreen_api_token
    environment:
      UGREEN_NAS_API_SCHEME: "https"
      UGREEN_NAS_API_PORT: "9999"
      UGREEN_NAS_API_VERIFY_SSL: "false"
    ports:
      - "4115:4115"
    restart: unless-stopped
