services:
  token-api:
    image: ghcr.io/tom-bom-badil/ugreen_api_token_proxy:latest
    container_name: ugreen_api_token_proxy
    ports:
      - "4115:4115"
    environment:
      UGREEN_NAS_API_SCHEME: "https"
      UGREEN_NAS_API_PORT: "9443"
      UGREEN_NAS_API_VERIFY_SSL: "false"
      LOG_LEVEL: "info"    # default=info, set to debug if needed.
      TZ: "Europe/Berlin"  # MUST be a valid TZ entry - relevant for log only.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
