name: Build and Push to GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./docker/ugreen_api_token
          file: ./docker/ugreen_api_token/Dockerfile
          push: true
          # tags: ghcr.io/${{ github.repository_owner }}/ugreen-api-token:latest
          tags: ghcr.io/tom-bom-badil/ugreen-api-token:latest
